### ISSUE TITLE
Which license does this repo have?

### ISSUE THREAD

**Issue by marco-tranzatto** [uscresl/piksi_ros#3]
Hi @hordurk , thanks for sharing this work in github! 
Can you please tell me which license this repo has? I used the `UDPDriver`, `UdpMulticaster` and `SbpUdpMulticastReceiver` classes into another repository that I would like to open source. Before doing it tough I need to know if you are ok with that and if you could put a license to this repo.

Thanks a lot.
Regards,
Marco.

**Comment by hordurk** [comment]
I've added a MIT license file to the project

**Comment by marco-tranzatto** [comment]
Thanks! :+1:
